export default [
	{ src: "/img/gallery/01.jpg", description: "Gallery Image 1" },
	{ src: "/img/gallery/02.jpg", description: "Gallery Image 2" },
	{ src: "/img/gallery/04.jpg", description: "Gallery Image 4" },
	{ src: "/img/gallery/03.jpg", description: "Gallery Image 3" },
	{ src: "/img/gallery/05.jpg", description: "Gallery Image 5" },
	{ src: "/img/gallery/04.jpg", description: "Gallery Image 4" },
	{ src: "/img/gallery/06.jpg", description: "Gallery Image 6" },
	{ src: "/img/gallery/02.jpg", description: "Gallery Image 2" },
	{ src: "/img/gallery/01.jpg", description: "Gallery Image 1" },
	{ src: "/img/gallery/03.jpg", description: "Gallery Image 3" },
	{ src: "/img/gallery/01.jpg", description: "Gallery Image 1" },
	{ src: "/img/gallery/04.jpg", description: "Gallery Image 4" },
	{ src: "/img/gallery/06.jpg", description: "Gallery Image 6" },
	{ src: "/img/gallery/02.jpg", description: "Gallery Image 2" },
	{ src: "/img/gallery/05.jpg", description: "Gallery Image 5" },
	{ src: "/img/gallery/03.jpg", description: "Gallery Image 3" },
	{ src: "/img/gallery/05.jpg", description: "Gallery Image 5" },
	{ src: "/img/gallery/06.jpg", description: "Gallery Image 6" },
] as const;
