export default [
	{ src: "/img/gallery/01.jpg", description: "Gallery Image 1", showOnHomepage: false },
	{ src: "/img/gallery/02.jpg", description: "Gallery Image 2", showOnHomepage: true },
	{ src: "/img/gallery/04.jpg", description: "Gallery Image 4", showOnHomepage: false },
	{ src: "/img/gallery/05.jpg", description: "Gallery Image 5", showOnHomepage: false },
	{ src: "/img/gallery/06.jpg", description: "Gallery Image 6", showOnHomepage: true },
	{ src: "/img/gallery/07.jpg", description: "Gallery Image 7", showOnHomepage: false },
	{ src: "/img/gallery/08.jpg", description: "Gallery Image 8", showOnHomepage: true },
	{ src: "/img/gallery/10.jpg", description: "Gallery Image 10", showOnHomepage: false },
	{ src: "/img/gallery/11.jpg", description: "Gallery Image 11", showOnHomepage: true },
	{ src: "/img/gallery/12.jpg", description: "Gallery Image 12", showOnHomepage: false },
	{ src: "/img/gallery/13.jpg", description: "Gallery Image 13", showOnHomepage: false },
	{ src: "/img/gallery/14.jpg", description: "Gallery Image 14", showOnHomepage: false },
	{ src: "/img/gallery/15.jpg", description: "Gallery Image 15", showOnHomepage: false },
	{ src: "/img/gallery/16.jpg", description: "Gallery Image 16", showOnHomepage: false },
	{ src: "/img/gallery/17.jpg", description: "Gallery Image 17", showOnHomepage: false },
	{ src: "/img/gallery/18.jpg", description: "Gallery Image 18", showOnHomepage: true },
	{ src: "/img/gallery/19.jpg", description: "Gallery Image 19", showOnHomepage: false },
	{ src: "/img/gallery/20.jpg", description: "Gallery Image 20", showOnHomepage: false },
	{ src: "/img/gallery/21.jpg", description: "Gallery Image 21", showOnHomepage: false },
	{ src: "/img/gallery/22.jpg", description: "Gallery Image 22", showOnHomepage: false },
	{ src: "/img/gallery/23.jpg", description: "Gallery Image 23", showOnHomepage: false },
	{ src: "/img/gallery/24.jpg", description: "Gallery Image 24", showOnHomepage: false },
	{ src: "/img/gallery/25.jpg", description: "Gallery Image 25", showOnHomepage: false },
	{ src: "/img/gallery/26.jpg", description: "Gallery Image 26", showOnHomepage: true },
	{ src: "/img/gallery/27.jpg", description: "Gallery Image 27", showOnHomepage: false },
	{ src: "/img/gallery/28.jpg", description: "Gallery Image 28", showOnHomepage: false },
] as const;
